# Generated by Django 5.2.5 on 2025-09-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_try_on', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tryonhistory',
            old_name='photo',
            new_name='user_photo',
        ),
        migrations.AddField(
            model_name='tryonhistory',
            name='result_image',
            field=models.ImageField(default=1, upload_to='tryon_results/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.ImageField(default='user_photos/', upload_to='uploads/'),
        ),
    ]
